name: Down Detector Test - MapasApp.com

on:
  schedule:
    - cron: "*/15 * * * *"

jobs:
  detector:
    runs-on: ubuntu-latest
    
    services:
      curlimages:
        image: curlimages/curl
        
    steps:
      - run: curl http://mapasapp.com || exit 1
      
